#+TITLE: ob-mermaid

Generate [[https://mermaidjs.github.io/][mermaid]] diagrams using org-mode, org-babel and [[https://github.com/mermaidjs/mermaid.cli][mermaid.cli]].

* Installation

  1. Install this package from source, as this fork is not avaialable from
     MELPA. For example, using elpaca:

     #+begin_src emacs-lisp
       (use-package ob-mermaid
         :elpaca (ob-mermaid
                  :host github
                  :depth nil
                  :repo "cfclrk/ob-mermaid"))
     #+end_src

  2. Install [[https://github.com/mermaidjs/mermaid.cli][mermaid.cli]]

  3. Specify =mmdc= executable path:

     #+begin_src elisp
       (setq ob-mermaid-cli-path "/your-installating-path/node_modules/.bin/mmdc")
     #+end_src

     This step isn't necessary if =(executable-find "mmdc")= already works.

  4. Add =mermaid= to =org-babel-load-languages=

     #+begin_src elisp
       (org-babel-do-load-languages
        'org-babel-load-languages
        '((mermaid . t)
          (scheme . t)
          (your-other-langs . t)))
     #+end_src

* Usage

  5. Open =org-mode= buffer and create an =org-babel= source block:

     #+begin_src org
       ,#+begin_src mermaid :file test.svg
         sequenceDiagram
           A-->B: Works!
       ,#+end_src
     #+end_src

     #+begin_src mermaid :file test.svg
       sequenceDiagram
         A-->B: Works!
     #+end_src

     #+RESULTS:
     [[file:test.svg]]

  6. To generate the diagram, you can either evaluate the source block or export
     the document. Note that the GitHub UI automatically renders the mermaid
     graph in the src block, even if there is no =#+RESULTS= block.

* Configuration

  =file= - Output file. It should be either svg, png or pdf.

  =width= - Width of the page. Optional.

  =height= - Height of the page. Optional.

  =theme= - Theme of the chart, could be default, forest, dark or neutral. Optional.

  =background-color= - Background color. Example: transparent, red, '#F0F0F0'. Optional.

  =mermaid-config-file= - JSON configuration file for mermaid. Optional.

  =css-file= - CSS file for the page. Optional.

  =pupeteer-config-file= - JSON configuration file for puppeteer. Optional.
